// <auto-generated />
namespace Financiera.Infraestructura.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DB01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB01));
        
        string IMigrationMetadata.Id
        {
            get { return "201703202133359_DB01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
